---
title: "Data Science Workflow"
author: "Matthew Edwards"
date: "09/07/2020"
output:
  revealjs::revealjs_presentation:
    #theme: night
    transition: none
    center: false
---

<style type="text/css">
  .reveal p {
    text-align: left;
  }
  .reveal ul {
    display: block;
  }
  .reveal ol {
    display: block;
  }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Data Science and Data Engineering

Data Science and Data Engineering are quite different

- **Data Engineering**: data storage, access and compute.
- **Data Science**: data exploration and induction.

*"You should only do engineering if you know what you are doing and you should only do science if you do not."* - Richard Hamming

Data Science is similar to **Statistics**

## Data Science - Data

Types of data:

- **Tabular**
- Text (Natural Language Processing)
- Images (Computer Vision)

## Data Science - Projects

Types projects:

- **Supervised Learning** (predict output)
- Unsupervised Learning
- Semi-supervised Learning
- Reinforcement Learning

Types of supervised learning:

- **Classification** (nominal output)
- Regression (numeric output)

## Data Science - Stages

Data Science stages for a supervised learning project:

- Data Tidying
- Data Splitting
- Exploratory Data Analysis
- Data Preprocessing
- Model Building
- Model Evaluation
 
These stages are **iterated** (not numbered).

# Data Tidying

Obtain [tidy data](https://vita.had.co.nz/papers/tidy-data.pdf):

1. Each variable forms a column.
2. Each observation forms a row.
3. Each type of observational unit forms a table

One of these variables is the *output* (to be predicted) and the others are *predictors*.

## Data Tidying

Data tidying requires some exploratory data analysis:

- Variable selection
- Data quality

# Data Splitting

Obtain two data sets:

1. **Training set**: this data set is used to build the model
2. **Test set**: this data set is used to evaluate the model

The test set is *only* used at the end of the project. The training set is also used for exploratory data analysis.

# Exploratory Data Analysis (EDA)

EDA is all about distributions. A distribution describes the variation within and between variables.

Types of distribution:

- predictor distributions
- predictor-output distributions
- predictor-predictor distributions

This stage affects data preprocessing and model building.

## Predictor Distributions

Numeric:

- Centre (e.g. mean)
- Spread (e.g. variance)
- Skewness
- Outliers

Nominal:

- Number of levels
- Sparsity
- Balance

## Predictor-output Distributions

Types of relationship:

- Weak or Strong
- Linear or Non-linear

## Predictor-predictor Distributions

These distributions are very important for model building.

# Data Preprocessing

Data Preprocessing is about transforming the data so that a model can processes it.

Often each model requires a different preprocessing pipeline.

EDA is used to suggest the variable transformations required by a model.

## Univariate Transformations

- Log / Box-Cox: remove skew
- Normalise: centre and scale
- Grouping: combining nominal levels

## Multivariate Transformations

- Linear Projection: strong linear predictor-predictor relationships
- Non-linear Projection: strong non-linear predictor-predictor relationships
- Combining variables manually: e.g. weight and height to BMI. 

# Model Building

Popular models include:

- Logistic Regression
- Random Forest
- Support Vector Machine

Each of these models has different preprocessing requirements.

# Model Evaluation

At this stage the model is evaluated for it's performance. However, how the model is evaluated can be decided early on in the workflow. 

Evaluation Metrics (classification):

- Accuracy: percent of correct predictions
- Sensitivity: percent of correct positive predictions
- Specificity: percent of correct negative predictions
- ROC Curve: Sensitivity and Specificity
- AUC: single measure of ROC Curve
- Cost Benefit measures: derived from Sensitivity and Spesificity

# Resources:

- Data Science with R
- tidymodels.org
