---
title: "Data Science Workflow"
author: "Matthew Edwards"
date: "09/07/2020"
output: 
  ioslides_presentation:
    widescreen: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Data Science

## Data Engineering

Data Science and Data Engineering differences:

- **Data Engineering**: data storage, access and compute.
- **Data Science**: data exploration and inference (e.g. prediction / explanation)

Data Science is similar to **Statistics**

## Data

Types of data:

- **Table data**
- Text data (Natural Language Processing)
- Image data (Computer Vision)

## Projects

Types of project:

- **Supervised Learning** (predict output)
- Unsupervised Learning 
- Semi-supervised Learning
- Reinforcement Learning (e.g. AI and Robotics)

Types of Supervised Learning:

- **Classification** (categorical output)
- Regression (numeric output)

## Stages

Data Science stages for a Supervised Learning project:

- Data tidying
- Data splitting
- Exploratory Data Analysis (EDA)
- Data pre-processing
- Model building / tuning
- Model evaluation

These stages are **iterated** (not numbered).

# Data Tidying

## Data Tidying

Obtain [tidy data form](https://vita.had.co.nz/papers/tidy-data.pdf):

1. Each variable forms a column
2. Each example forms a row

This form is required for most Data Science tools. One variable is the *output* (to be predicted) and the other variables are the *inputs*.

# Data Splitting

## Data Splitting

Obtain two data sets:

1. **Training data**: used to build / tune the model (e.g. past exam papers)
2. **Testing data**: used to evaluate the model (e.g. exam paper)

The testing data is *only* used for model evaluation. The training data is used for everything else.

# Exploratory Data Analysis

## Overview

EDA is all about distributions. A distribution describes the variation within and between variables.

Types of distribution:

- Input and output distributions
- Input-output distributions
- Input-input distributions

This stage affects data pre-processing and model building / tuning.

## Input Distributions (numeric)

Explored using **histograms**:

- Centre (e.g. mean)
- Spread (e.g. variance)
- Skewness
- Outliers

## Input Distributions (categorical)

Explored using **bar charts**:

- Number of classes
- Sparsity
- Balance

## Input-output Distributions

Explored using **scatter plots**:

- Weak or strong associations
- Linear or non-linear associations

# Data Pre-processing

## Data Pre-processing

Data Pre-processing is about transforming the data so that a model can processes it. EDA motivates variable transformations.

Univariate Transformations: 

- **Log**: remove skewness
- **Normalise**: centre and scale

# Model Building

## Model Building

Popular classification models include:

- Logistic Regression
- Random Forest
- Support Vector Machine
- k-Nearest Neighbours

# Model Evaluation

## Model Evaluation

At this stage the model is evaluated for it's performance. 

Classification evaluation metrics:

- Accuracy (% correct predictions)
- Sensitivity (% correct predictions of positive class)
- Specificity (% correct predictions of negative class)
- Cost / benefit measures

# Resources

## Resources

- [R for Data Science](https://r4ds.had.co.nz/)
- https://www.tidymodels.org/
- Slides: https://mt-edwards.github.io/data-science/
